### ISSUE TITLE
Option to use tabview as mysql pager

### ISSUE THREAD

**Issue by firecat53** [firecat53/tabview#120]
This works from command line using mysql -e 'query' | tabview -

However, it needs to have quoting=csv.QUOTE_NONE set (line 1106 tabview.py).

To be used from the interactive console, you have to start mysql client with the -s parameter to suppress the table characters.

Edit: for the interactive client, add these lines to ~/.my.cnf:

    pager=tabview -d '\t' -
    silent

This still still needs quoting set to none, however, to catch quoting issues within fields.

**Comment by scls19fr** [comment]
In my mind, we might release Pandas stuff first...
because when it will be done it will be easier to create a MySQL, PostGreSQL (or any database supported by SQLAlchemy in fact) pager as Pandas provide `read_sql` method http://pandas.pydata.org/pandas-docs/stable/generated/pandas.io.sql.read_sql.html
but that's a different approach an it won't make it directly usable from Bash using pipe.

**Comment by wavexx** [comment]
This might just be csvsniff not detecting the quoting style properly.

**Comment by firecat53** [comment]
It appears that csv.Sniffer.sniff doesn't identity QUOTE_NONE. If there are no quotes at all, it will still default to QUOTE_MINIMAL.
